version: "3.8"

networks:
  loki:

volumes:
  loki:

services:
  # Since the Loki containers are running as user 10001 and the mounted data volume is owned by root,
  # Loki would not have permissions to create the directories.
  # Therefore the init container changes permissions of the mounted directory.
  init:
    image: &lokiImage grafana/loki:3.1.0
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/loki"
    volumes:
      - ./loki:/loki
    networks:
      - loki
    container_name: init

  loki-gateway:
    image: nginx:1.27
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "3100"
    networks:
      - loki
    depends_on:
      - loki-read
      - loki-write
      - loki-backend  
    container_name: loki-gateway

  loki-read:
    image: *lokiImage
    volumes:
      - ./config:/etc/loki/
    # only needed for interactive debugging with dlv
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - apparmor=unconfined
    ports:
      - "3100"
      - "7946"
      # uncomment to use interactive debugging
      # - "40000-40002:40000" # makes the replicas available on ports 40000, 40001, 40002
    command: "-config.file=/etc/loki/loki.yaml -target=read -legacy-read-mode=false"
    networks:
      - loki
    restart: always
    container_name: loki-read
    depends_on:
      - init
    deploy:
     mode: replicated
     replicas: 3

  loki-write:
    image: *lokiImage
    volumes:
      - ./config:/etc/loki/
    # only needed for interactive debugging with dlv
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - apparmor=unconfined
    ports:
      - "3100"
      - "7946"
      # uncomment to use interactive debugging
      # - "50000-50002:40000" #  makes the replicas available on ports 50000, 50001, 50002
    command: "-config.file=/etc/loki/loki.yaml -target=write"
    networks:
      - loki
    depends_on:
      - init
    restart: always
    container_name: loki-write
    deploy:
     mode: replicated
     replicas: 3

  loki-backend:
    image: *lokiImage
    volumes:
      - ./config:/etc/loki/
      - ./rules:/loki/rules:ro
    # only needed for interactive debugging with dlv
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - apparmor=unconfined
    ports:
      - "3100"
      - "7946"
      # uncomment to use interactive debugging
      # - "60000-60002:40000" #  makes the replicas available on ports 60000, 60001, 60002
    command: "-config.file=/etc/loki/loki.yaml -target=backend -legacy-read-mode=false"
    networks:
      - loki
    depends_on:
      - init
    restart: always
    container_name: loki-backend
    deploy:
     mode: replicated
     replicas: 3

